---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: conjur-appliance
---
apiVersion: v1
kind: Service
metadata:
  name: conjur-appliance
  labels:
    app: conjur-appliance
spec:
  ports:
  - port: 443
    name: https
  selector:
    app: conjur-appliance
  type: LoadBalancer
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: conjur-appliance
  name: conjur-appliance
spec:
  port:
    targetPort: https
  to:
    kind: Service
    name: conjur-appliance
  tls:
    termination: reencrypt
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: conjur-appliance
  name: conjur-appliance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conjur-appliance
  template:
    metadata:
      labels:
        app: conjur-appliance
    spec:
      serviceAccountName: conjur-appliance
      hostAliases:
      - ip: "{LAB_IP}"
        hostnames:
        - "mysql.{LAB_DOMAIN}"
      containers:
      - image: default-route-openshift-image-registry.apps-crc.testing/conjur/conjur-appliance
        imagePullPolicy: IfNotPresent
        name: conjur
        env:
          - name: DBADDR
            value: mysql.{LAB_DOMAIN}
          - name: DBUSER
            value: conjur
          - name: DBPASS
            value: Cyberark1
        ports:
        - containerPort: 443
          name: https
